# Generated by Django 4.0.5 on 2022-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=3)),
                ('courseName', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=2)),
                ('batch', models.CharField(max_length=10)),
            ],
        ),
    ]
