# Generated by Django 4.0.5 on 2022-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID1', models.CharField(max_length=5)),
                ('courseName', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=5)),
                ('batch', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
