# Generated by Django 4.0.5 on 2022-06-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_coursetable_delete_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetable',
            old_name='courseID1',
            new_name='courseID',
        ),
    ]
